### ISSUE TITLE
M_PI Deprecated

### ISSUE THREAD

**Issue by Polaris33** [dthain/QMC5883L#1]
This is my first post so please understand improper terms.  When I compile my program it fails on M_PI which is buried inside of your library line 200.  The little research I did indicates that this has been deprecated in the AVR math library.  I  am using Arduino 1.6.11 Compiler.
Thanks
Doug
An eager hobbyist 

  float fx = (float)x/(xhigh-xlow);
  float fy = (float)y/(yhigh-ylow);
  int heading = 180.0*atan2(fy,fx)/M_PI;
  if(heading<=0) heading += 360;

**Comment by dthain** [comment]
@Polaris33 thanks for the heads-up, a patch is incoming shortly.

**Comment by dthain** [comment]
Please try the latest commit and see if it works for you.

**Comment by dthain** [comment]
@Polaris33 I believe this is fixed, please re-open if you have a problem.
