### ISSUE TITLE
Missing Wire.begin()

### ISSUE THREAD

**Issue by GaryBoone** [dthain/QMC5883L#10]
The example code in examples/compass/compass.ino won't run as is because Wire.begin() isn't called. 

It's easily solved with:

#include <Wire.h>

Setup() {
  Wire.begin() 
...

However, ideally QMC5883L.cpp would initialize Wire iff it has not been so the Wire usage is fully encapsulated.

**Comment by dthain** [comment]
@GaryBoone thanks for the tip, the library is fixed in v1.0.6
Let me know if it works for you.

**Comment by GaryBoone** [comment]
Looks like the change is:

  /* Initialize Wire only if not already done. */
  if(TWCR==0) Wire.begin();

src/QMC5883L.cpp: In member function 'void QMC5883L::init()':
src/QMC5883L.cpp:149:6: error: 'TWCR' was not declared in this scope

Where is TWCR declared?

**Comment by dthain** [comment]
AFAIK, the Wire library does not provide any method for determining if Wire.begin has already been called, so you need to look at the underlying hardware to see if it has been initialized.

TWCR is an Arduino hardware register, it should be part of the base compile environment:
https://playground.arduino.cc/Main/WireLibraryDetailedReference

What environment are you compiling in?
This works for me on Arduino 1.8.5 compiling for Arduino Uno and several other boards..

**Comment by dthain** [comment]
Ah, you had the right suggestion in the first place, which is more portable.
Fixed in v1.0.8.
