### ISSUE TITLE
compass stop working after couple of minutes 

### ISSUE THREAD

**Issue by mkeyno** [dthain/QMC5883L#4]
hi I bought GY-271 3.3 volt external compass QMC5883L and it cease to working after  couple of minutes  and it should reset to start working again , I really appreciated for any hint

**Comment by dthain** [comment]
Sorry, I haven't experienced that myself, so I don't have any insight into the problem.
I'll leave this issue open in case anyone else runs into it and can comment.

**Comment by onionstack** [comment]
@mkeyno ：Hello, is it because your compass is disturbed by the magnetic field?
