### ISSUE TITLE
This function will never return an Angle.

### ISSUE THREAD

**Issue by onionstack** [dthain/QMC5883L#5]
I don't know if this is your code error or what, this function never returns an Angle.

```
int QMC5883L::readHeading()
{
  int16_t x, y, z, t;

  if(!readRaw(&x,&y,&z,&t)) return 0;

  /* Update the observed boundaries of the measurements */

  if(x<xlow) xlow = x;
  if(x>xhigh) xhigh = x;
  if(y<ylow) ylow = y;
  if(y>yhigh) yhigh = y;

  /* Bail out if not enough data is available. */
  
  if( xlow==xhigh || ylow==yhigh ) return 0;

  /* Recenter the measurement by subtracting the average */

  x -= (xhigh+xlow)/2;
  y -= (yhigh+ylow)/2;

  /* Rescale the measurement to the range observed. */
  
  float fx = (float)x/(xhigh-xlow);
  float fy = (float)y/(yhigh-ylow);

  int heading = 180.0*atan2(fy,fx)/M_PI;
  if(heading<=0) heading += 360;
  
  return 1;
}
```

**Comment by dthain** [comment]
Good grief, that's a dumb mistake on my part, thanks for pointing it out.
I believe it's fixed in the latest master and release 1.0.3.
Please let me know if it works for you.

**Comment by L-eeX** [comment]
@dthain ：There is no processing of the z-axis data in the program. Can you draw the roll Angle and the pitch Angle?

**Comment by onionstack** [comment]
@dthain : There is no processing of the z-axis data in the program, can you calculate roll Angle and pitch Angle?

**Comment by dthain** [comment]
It's not possible to measure roll and pitch in the general case using only a magnetometer, simply because the Earth's magnetic field runs north-to-south.  If you want roll and pitch, use an accelerometer/gyro like the MPU6050 which observes orientation relative to the up-down force of gravity.

**Comment by onionstack** [comment]
@dthain ：I want to know what's the use of the z-axis data?
                  When the compass is disturbed by a magnetic field, will it stop reading data until it is corrected?
