### ISSUE TITLE
Calibration

### ISSUE THREAD

**Issue by Seabrand** [dthain/QMC5883L#9]
Hi, thanks for sharing your code, very inspiring.
However, you may consider allowing to stop auto-calibration at some point. When you now point even a magnetic screwdriver at the sensor, the range becomes useless until you switch everything off (or perhaps only Soft Reset). Potential security hazard ;)

**Comment by dthain** [comment]
Indeed - An nice way to do this would be to collect N readings in each of M fixed radial slices, then halt calibration.
